### ISSUE TITLE
Song Request Issues 

### ISSUE THREAD

**Issue by EngineerBean** [SaxyPandaBear/TwitchSongRequests#265] opened 2024-03-02 19:27 UTC
### What happened?

Thx for the onboarding once again. After multiple tries and confirming that both Twitch and Spotify are both connected and the Reward Request is present as it should be I am trying to test this feature and neither URLs or just using keywords are working. I have no idea where I might of gone wrong. Twitch name 'Beandownunder' email 'jpharding75@gmail.com'

### What part of the service is not working for you?

Other (please describe above)

**Comment by SaxyPandaBear** [comment] 2024-03-03 21:41
Ok there might actually be an issue on my end. I'm seeing a bunch of failures. I think Spotify changed their API

```
@deployment:5dadf302-6486-4832-bfc3-4e857c2297cd @error:"failed to get track 3wrYE5qNNTO6YFkgoxorlL: json: cannot unmarshal number 640.0 into Go struct field Image.album.images.width of type int"
```

**Comment by SaxyPandaBear** [comment] 2024-03-03 21:48
I'm keeping tabs on https://github.com/zmb3/spotify/pull/251 in case a fix comes through with an updated library version. I don't really want to fork the project to fix it myself if I don't have to but idk how long it'll take to push a patched version

**Comment by S4MARON** [comment] 2024-03-03 23:04
Thank you, I appreciate your effort.  Do you have a ko-fi site or something?

**Comment by SaxyPandaBear** [comment] 2024-03-05 11:19
Technically this is a duplicate of #264 , now that I know that everyone's having the same issue. Closing this one out in favor of the issue that was raised before it

**Closed by SaxyPandaBear** 2024-03-05 11:19 UTC
Labels: bug
