### ISSUE TITLE
[Bug]: [Describe the issue]

### ISSUE THREAD

**Issue by Poketick** [SaxyPandaBear/TwitchSongRequests#211] opened 2023-08-25 19:38 UTC
### What happened?

I have "successfully subscribed" on the website link where I authorized both my twitch and spotify. I have also completed the onboard request and a channel point redemption was created on my channel (this led me to assume it worked). I started playing a song on spotify to activate it, and had a chatter redeem their song via the channel point redemption. However, the song did not pop up on my spotify app queue.

My twitch username is gabesu

### What part of the service is not working for you?

The song that is redeemed will not pop up on spotify.

**Comment by SaxyPandaBear** [comment] 2023-08-25 19:41
The onboarding is manual. The problem is that in order to interact with the Spotify API, I have to purposefully add your Spotify account to my allowlist of users that can use my service. Spotify only lets me have 25 users, and I am maxed out. Please wait for me to get to your onboarding request before it works, or you can try to host it yourself. I have been super busy so I haven't worked on that but my plan is to make it easy to self-host so you don't have to rely on me. See #205 

I'm going to close this because this is expected because I haven't gotten to your onboarding request #210 yet

**Closed by SaxyPandaBear** 2023-08-25 19:41 UTC
Labels: bug

**Comment by Poketick** [comment] 2023-08-25 19:45
Ah I understand. Thank you for the quick response!
